name: tobacco_pos
description: A Tobacco POS Flutter application (demo)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/products.json
    - assets/sales.json
